apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gradio-hello-world
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - name: gradio-hello-world-1
        image: us-central1-docker.pkg.dev/cicd-system-demo-01/gradio-hello-world/gradio-hello-world:v5
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: API_KEY
          value: XXXXXXXXXX
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - percent: 100
    latestRevision: true